openapi: 3.0.3
info:
  title: LeadSquared Portals
  version: 1.0.0
  description: Generated by postman_to_openapi 1.0.0
servers:
- description: Singapore
  url: https://portalapi.leadsquared.com/
- description: United States
  url: https://portalapi-us11.leadsquared.com/
- description: India Mumbai
  url: https://portalapi-in21.leadsquared.com/
- description: India Hyderabad
  url: https://portalapi-in22.leadsquared.com/
- description: Ireland
  url: https://portalapi-ir31.leadsquared.com/
- description: Canada
  url: https://portalapi-ca12.leadsquared.com/
- description: Dubai
  url: https://portalapi-me61.leadsquared.com/
tags:
- name: Access
- name: Authentication
- name: Auto Login
- name: Settings
- name: Widgets
x-tagGroups:
- name: LeadSquared Portals APIs > Access
  tags:
  - Access
- name: LeadSquared Portals APIs > Authentication
  tags:
  - Authentication
- name: LeadSquared Portals APIs > Auto Login
  tags:
  - Auto Login
- name: LeadSquared Portals APIs > Settings
  tags:
  - Settings
- name: LeadSquared Portals APIs > Widgets
  tags:
  - Widgets
paths:
  /api/Access/PublicToken:
    get:
      summary: Get Public Auth Key
      operationId: get_public_auth_key
      tags:
      - Access
      responses:
        '200':
          description: Get Public Auth Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  PublicAuthKey:
                    type: string
                    description: 'This is public authentication key. This key does
                      not have an expiration time.


                      '
              example:
                PublicAuthKey: QXFwU1VQbnRsZmhyam9qbkZUM3VtQng4ZlgxbkVHMmdZQThXblRaQytaSXg0K0JFbmRqMU5pNFIvWGJVL0ZjR3ZNMlo0KzduQzZlcXFPaUY4a1hneDBHUlB0b1A3bnVHG9EenJyTnpnZWhqa1lnS1JGK2MvakRDOTJrM3FDQlEzVj
      description: "Before you can use the Portal Authentication APIs, you need to\
        \ obtain a public authentication key.\n\n- This API requires you to make a\
        \ GET request and pass your LeadSquared [Access Key and Secret Key](https://apidocs.leadsquared.com/authentication/)\
        \ in the query string.\n    \n- You will receive the public authentication\
        \ key in the response.\n    \n\n**Note:**\n\n- This key does not have an expiration\
        \ time.\n    \n- You must also pass a registration token generated by the\
        \ [Get Portal Registration Token API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/mpjd2cu/get-portal-registration-token?action=share&source=copy-link&creator=39502170&ctx=documentation)\
        \ as a header to the [Register User API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/7wjg5re/register?action=share&source=copy-link&creator=39502170&ctx=documentation)."
      parameters: []
      security:
      - AccessKey: []
        SecretKey: []
  /api/Access/GetRegisterToken:
    get:
      summary: Get Portal Registration Token
      operationId: get_portal_registration_token
      tags:
      - Access
      responses:
        '200':
          description: Get Portal Registration Token
          content:
            application/json:
              schema:
                type: string
              example: 89a2423b35820b60f14c7f012d93c55de
      description: "Returns registration token for LeadSquared Portals.\n\nAlong with\
        \ the [Public Auth Key](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/hsw4gfr/get-public-auth-key?action=share&source=copy-link&creator=39502170&ctx=documentation),\
        \ the response returned by this API must also be pass as a header in the [Register\
        \ User API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/7wjg5re/register?action=share&source=copy-link&creator=39502170&ctx=documentation).\n\
        \n- Pass your `accessKey` and `secretKey` in the API URL.\n    \n- Pass the\
        \ registration token returned in the response as a header in the [Register\
        \ User API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/7wjg5re/register?action=share&source=copy-link&creator=39502170&ctx=documentation).\n\
        \    \n    - For example, x-lsq-registertoken = xxxx"
      parameters: []
      security:
      - AccessKey: []
        SecretKey: []
  /api/Authentication/V2/Register:
    post:
      summary: Register
      operationId: register
      tags:
      - Authentication
      responses:
        '200':
          description: Register with Phone
          content:
            application/json:
              schema:
                type: object
                properties:
                  LeadId:
                    type: string
                    description: The unique identifier of the lead that was registered
                      or updated as a portal user.
                  Message:
                    type: string
                    description: A status message indicating the result of the registration
                      request. Returns `Registration Successful` on success.
                  SiginResponse:
                    type: object
                    properties:
                      AuthKey:
                        type: string
                        description: A private authentication token issued to the
                          registered portal user. This token has a default expiry
                          time of 4 hours and can be used to authenticate subsequent
                          portal API requests.
                      LeadId:
                        type: string
                        description: The unique identifier of the registered lead.
                          Same value as the top-level LeadId.
                    description: Contains the authentication details generated upon
                      successful registration.
              example:
                LeadId: ad7ea8a4-a6ff-4a22-8948-6e72495137c7
                Message: Registration Successful
                SiginResponse:
                  AuthKey: aVBGbVFnTWszTW5IeWphM0hQZWhUOFA3em5OckpJeUJndXlSNTFvRVZMc3ZKZFlCbjhpUVczc2J5WHlFUDdsZTZEQUhrR3ZLNUpPRWdGb251LzJXOXhEZ2JlWnNub2RLSkJoK2hHeG02UUVCSnVwREp1cVZ1WDIybUpZN21KWWU3ZGlIZ3dxTDF3OWZFZFNpWU1OZER5WHJ1cjNXMGtCcWtDZWY2SGJrMWVIaHozamtPNERacmZxVHlEdGx2bENNVUN6bmxsbjZBZ01zUGFwbWNmY0Zob2dxR3NZOXFUdHN2RnB0aTFKUldHTHVHZWpoTElqNlV2ZnM2UHg3Z3daSGpCQW1MUlBLbkRVVkE5ZUF3N3RjVmlnaUt5TU5mTzhEOFdua0h3NUd0K0pNdzR02SU5SMlRNMmE1Q1VpRERWVHpsamdnS2UvQnl5blBlY0xkRjhHWmxBZnAweHJkZ3Z0WHhDRk5FSU02R2x4Ny9VbDlWRVlORWh1c0lOd0pONFJVUHBYMUNReWVhVzRLYmR1R0s1c1NJM1h1UFE0ZUgvSmZ6WEtCNWNxMlN1WG5rY0JoemRSdHhCMWpUeTh6amsyQ3RTc3FSb0YvMkRBQWxpcmJYTXZuN1M4VGNWbHZaVEZ1UmVlVTdxUlQ3ZjZYOXZzdEZ1UkdyOWdmRTZ2U00wZTUybm9jK0l6M1hRb2hBMTNNc2FNVThVZ0JUeHVGa29XUFBYTEtw
                  LeadId: ad7ea8a4-a6ff-4a22-8948-6e72495137c7
      description: "Registers a lead as a portal user. If the lead already exists\
        \ in your account, the lead will get updated as a portal user. If the lead\
        \ doesn’t exist, a new lead will get created in your account.\n\n> Note: It\
        \ returns a private token - `AuthKey` , which has 4 hours of default expiry\
        \ time. \n  \n\n### Payload\n\nYou may pass additional lead attributes, however,\
        \ it is mandatory to pass the following attributes in the JSON body –\n\n\
        - `mx_Portal_Password`\n    \n- `mx_Portal_Confirm_Password`\n    \n- Any\
        \ unique lead identifier in your account (`EmailAddress` , `Phone` , `mx_PAN_Number`,\
        \ etc.). If you pass multiple unique lead identifiers in the list, the first\
        \ identifier in the list will be used to search the lead.\n    \n\n| **Parameter**\
        \ | **Description** | **Data Type** | **Required** |\n| --- | --- | --- |\
        \ --- |\n| `RegisterOnlyNewLead` | If passed as `true`, only new leads will\
        \ be registered as portal users. An exception will be returned in case of\
        \ existing leads. | `Boolean` | No |\n| `LeadFields` | Pass the Attribute\
        \ (Schema names of lead fields) and Value of the lead fields you want to accept.\
        \ | `String` | Yes |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                LeadFields:
                  type: array
                  items:
                    type: object
                    properties:
                      Attribute:
                        type: string
                      Value:
                        type: string
                  description: Pass the Attribute (Schema names of lead fields) and
                    Value of the lead fields you want to accept.
                RegisterOnlyNewLead:
                  type: boolean
                  description: If passed as `true`, only new leads will be registered
                    as portal users. An exception will be returned in case of existing
                    leads.
              required:
              - LeadFields
            example:
              LeadFields:
              - Attribute: mx_Portal_Confirm_Password
                Value: password@123
              - Attribute: mx_Portal_Password
                Value: password@123
              - Attribute: EmailAddress
                Value: johnwick@acme.com
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Authentication/V2/Signin:
    post:
      summary: Sign In with Password
      operationId: sign_in_with_password
      tags:
      - Authentication
      responses:
        '200':
          description: Sign In with Phone & Password
          content:
            application/json:
              schema:
                type: object
                properties:
                  AuthKey:
                    type: string
                    description: A private authentication token issued to the registered
                      portal user. This token has a default expiry time of 4 hours.
                  LeadId:
                    type: string
                    description: The unique identifier of the signed-in lead.
              example:
                AuthKey: dTlFZGFSMG1KVGFreHVybmkyRk5rQnlZVm9JUDJCTlBEYlp3Y3hzVkU1bHZQOGNFbU5VTWRDUERkMnF2TUhjY1RhcDZhMXQ2TmxXaE9QeUNSOHlXc0FGYUFkaG9Gb2ZMN2JlTmFSWUgweUluczhZOFhFdGtoZ3BMaVd3TzNJd2RJOE9XUGdyKzB0TjhLWjduZWhqMW5CbXlZclFOOFhsbUtYYjRDeFV2YjhQV0NURUR0T2d0SjR3UlRPN0ZyYXpiSWpOa0tmckhZZWVoN1JPeDMxUmNQTmM0NklVSHdnVEwyczBKRjlvNWNzMXoyeXZlQkNCakQ0aFVsR3dMc2JqZU5OaU9mdWZDNmdIbGU0WkFNQU1RMWJzNmtHK05PN0c2d1RtdEE1WTZHOG5ua0NwNDBpTEgrb2VsUjVqWVhQTWtEbEt3YWhDc1JKdU5VQWxzVGpHSURDYWpTQkJkbWN3b3IrYzA5VHkxbVVZUU42SERKTFVJV2tKUWNuSzVsQjNkaitid3RxWTFDWktJb2I3TmxYQ25oSTlZSExqaWdLVHRjb0g5VGQ1dk1PR3dlMmFhMkQzTDV1WFhEanV3bnRlbzNpVFZoWjNjZ1ltbzMrN25WTGovQlIxcEJnQWlTVUN2dWVyQm1uSzYvMmpWQ2liVzhiaWh6eUdPN3dpdFd6UkZFMkJ6Mko4NVh0TGlFOWpXSEhOSWtNSUNhQ0dUNWd1eEhtbGk0OElhak5reGZvYkRDRllzTTE4NGh6aEtQUzJDajN6b2d5dTJ0Vm8zcC9Ydkp2NGJkU3ArUk1PZ0w2MzhLMXQzWDFYOXBJMWR0WE1LaFgyQVl3Tng4TU5TREIybC9ZbEFDdzBuREx3WTRMaEQveUpFYlpldlc0SnRpclpEd2ZibmxqTkNZaGtEOWxiajZqSGJLcTlJSVM5VHduek5WZHJSZ0xjUGNEMk1jUEN4YS9PRDROU1BxVXpIbVBMdzR2R3NSMnlNSWdxcWlJOGJmT2dCU1RSWUVYWEM2OFRxYzhIZXkxdTc2cXdBeFRoRHMvRlVyZWEzMHRaQ1RBd0c4azZva2hiWXF1cnVUTGFqSkNXYzlzdjRzV0ROeVlrd2FSemhNcEZuUVFUY00rdTBkZXU1MGc9PQ==
                LeadId: e4083488-d183-4281-ac9d-e1d101d4ee9c
      description: "This API signs in a [registered user](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/7wjg5re/register?action=share&source=copy-link&creator=39502170&ctx=documentation).\
        \ Once signed in, the user will have access to the custom functionality developed\
        \ within your portal (for example, loan/education application forms, progress\
        \ tracking, contact information, etc.).\n\n> **Note:** It returns a private\
        \ token - `AuthKey` , which has 4 hours of default expiry time. \n  \n\n##\
        \ Payload\n\n| **Parameter** | **Description** | **Data Type** | **Required**\
        \ |\n| --- | --- | --- | --- |\n| `EmailAddress` | Pass the user’s registered\
        \ email address. | `String` | Pass either `EmailAddress` or `SearchKeyData`\
        \ |\n| `Password` | Pass the user’s password. | `String` | Yes |\n| `SearchKeyData`\
        \ | Alternatively, you can pass the `SearchKeyData` property and include the\
        \ `SchemaName` and `Value` of any unique lead field. For example, you can\
        \ sign in with the Phone Number. | `String` | Pass either `EmailAddress` or\
        \ `SearchKeyData` |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                EmailAddress:
                  type: string
                  description: 'Pass the user’s registered email address.


                    > Note: You must pass either `EmailAddress` or `SearchKeyData`.'
                Password:
                  type: string
                  description: Pass the user’s password.
                SearchKeyData:
                  type: array
                  description: 'Alternatively, you can pass the `SearchKeyData` property
                    and include the `SchemaName` and `Value` of any unique lead field.
                    For example, you can sign in with the Phone Number.


                    > Note: You must pass either `EmailAddress` or `SearchKeyData`.'
                  items:
                    properties:
                      SchemaName:
                        type: string
                      Value:
                        type: string
                    type: object
              required:
              - Password
            example:
              EmailAddress: johnwick@example.com
              Password: Samplepassword@123
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Authentication/V2/SigninOTP/Get:
    post:
      summary: Get Sign In OTP
      operationId: get_sign_in_otp
      tags:
      - Authentication
      responses:
        '200':
          description: Getting OTP on Phone
          content:
            application/json:
              schema:
                type: object
                properties:
                  Code:
                    type: string
                    description: An encrypted verification code that must be passed
                      along with the OTP in the Sign-In with OTP API to complete authentication.
                  FieldContent:
                    type: string
                    description: The email address or phone number to which the OTP
                      was sent.
                  Message:
                    type: string
                    description: A status message indicating the result of the request.
                      On success, it specifies the destination to which the OTP was
                      sent.
                  SigninFieldCode:
                    type: string
                    nullable: true
                    description: Reserved for internal use. Returns null in standard
                      responses.
                  Status:
                    type: string
                    description: The overall result of the OTP request. Returns Success
                      when the OTP is sent successfully.
              example:
                Code: WWcyemllZ2l4OG9UeFdzT05IVVZJQjhEeXdJZlpoTTdYMHJ6OGVvUmU0bGh4eWY4bWFncllMbnErMGdFTG85ZjVaQnNCeVViZkYxQlJKTGRPemRpWnREWlhRbXhiaEQ4OGhTYTNLRXNRTEVqNmpOaVkvM0tnUmVVbytVM1dFbUpMMTZ1T3kzNkJIZTl2ZXpoWkpHNGxFdHhNVXFJcHR2cElLTEoxd1ZwKzBGUDhSNERUaHdhbW9MSUFPaG56UDVrNkRFZk9GTGUvTVIzZFBOUk5pTGdoYjhHeHltY3JxMDdSQkNhUmZ1dXU2Q1dqd0F6S2VJSHlhYTgxdndHSUlMa3FBQ2JTdWZydUlIeHMrWFl6cXk1aVE9PQ==
                FieldContent: +91-1234567890
                Message: OTP successfully sent to +91-1234567890
                SigninFieldCode: null
                Status: Success
      description: "Returns a One-Time Password (OTP) on Email or SMS that can be\
        \ used to sign-in a user.\n\n**Note:**\n\n- The `Code` and `FieldContent`\
        \ returned from the response (together with the OTP received on the user’s\
        \ phone) must be passed in the Sign-In with OTP API.\n    \n- The OTP is valid\
        \ for a default duration of 10 minutes. this can be increased by contacing\
        \ [support@leadsquared.com.](https://mailto:support@leadsquared.com)\n   \
        \ \n\n## Payload\n\n| **Parameter** | **Description** | **Data Type** | **Required**\
        \ |\n| --- | --- | --- | --- |\n| `FieldSchemaName` | Pass a unique identifer\
        \ of either `EmailAddress` or `Phone` . | `String` | Yes |\n| `FieldContent`\
        \ | The OTP will be sent to the phone number or email address specified in\
        \ the `FieldContent` parameter. | `String` | Yes |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                FieldSchemaName:
                  type: string
                  description: Pass a unique identifier of either `EmailAddress` or
                    `Phone`.
                FieldContent:
                  type: string
                  description: The OTP will be sent to the phone number or email address
                    specified in the `FieldContent` parameter.
              required:
              - FieldSchemaName
              - FieldContent
            example:
              FieldSchemaName: EmailAddress
              FieldContent: johnwick@example.com
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Authentication/V2/Signin__2:
    post:
      summary: Sign In with OTP
      operationId: sign_in_with_otp
      tags:
      - Authentication
      responses:
        '200':
          description: Sign In with Phone OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  AuthKey:
                    type: string
                    description: A private authentication token. This token has a
                      default expiry time of 4 hours.
                  LeadId:
                    type: string
                    description: The unique identifier of the signed-in lead.
              example:
                AuthKey: dTlFZGFSMG1KVGFreHVybmkyRk5rQnlZVm9JUDJCTlBEYlp3Y3hzVkU1bHZQOGNFbU5VTWRDUERkMnF2TUhjY1RhcDZhMXQ2TmxXaE9QeUNSOHlXc0FGYUFkaG9Gb2ZMN2JlTmFSWUgweUluczhZOFhFdGtoZ3BMaVd3TzNJd2RJOE9XUGdyKzB0TjhLWjduZWhqMW5CbXlZclFOOFhsbUtYYjRDeFV2YjhQV0NURUR0T2d0SjR3UlRPN0ZyYXpiSWpOa0tmckhZZWVoN1JPeDMxUmNQTmM0NklVSHdnVEwyczBKRjlvNWNzMXoyeXZlQkNCakQ0aFVsR3dMc2JqZU5OaU9mdWZDNmdIbGU0WkFNQU1RMWJzNmtHK05PN0c2d1RtdEE1WTZHOG5ua0NwNDBpTEgrb2VsUjVqWVhQTWtEbEt3YWhDc1JKdU5VQWxzVGpHSURDYWpTQkJkbWN3b3IrYzA5VHkxbVVZUU42SERKTFVJV2tKUWNuSzVsQjNkaitid3RxWTFDWktJb2I3TmxYQ25oSTlZSExqaWdLVHRjb0g5VGQ1dk1PR3dlMmFhMkQzTDV1WFhEanV3bnRlbzNpVFZoWjNjZ1ltbzMrN25WTGovQlIxcEJnQWlTVUN2dWVyQm1uSzYvMmpWQ2liVzhiaWh6eUdPN3dpdFd6UkZFMkJ6Mko4NVh0TGlFOWpXSEhOSWtNSUNhQ0dUNWd1eEhtbGk0OElhak5reGZvYkRDRllzTTE4NGh6aEtQUzJDajN6b2d5dTJ0Vm8zcC9Ydkp2NGJmxqTkNZaGtEOWxiajZqSGJLcTlJSVM5VHduek5WZHJSZ0xjUGNEMk1jUEN4YS9PRDROU1BxVXpIbVBMdzR2R3NSMnlNSWdxcWlJOGJmT2dCU1RSWUVYWEM2OFRxYzhIZXkxdTc2cXdBeFRoRHMvRlVyZWEzMHRaQ1RBd0c4azZva2hiWXF1cnVUTGFqSkNXYzlzdjRzV0ROeVlrd2FSemhNcEZuUVFUY00rdTBkZXU1MGc9PQ==
                LeadId: e4083488-d183-4281-ac9d-e1d101d4ee9c
      description: "This API signs-in a [registered user](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/7wjg5re/register?action=share&source=copy-link&creator=39502170&ctx=documentation).\
        \ Once signed in, the user will have access to the custom functionality developed\
        \ within your portal (for example, loan/education application forms, progress\
        \ tracking, contact information, etc.).\n\n> **Note:** Before calling this\
        \ API you must get the OTP data using the [Get Sign In OTP API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/90hgnzn/get-sign-in-otp?action=share&source=copy-link&creator=39502170&ctx=documentation).\
        \ \n  \n\n## Payload\n\n| **Parameter** | **Description** | **Data Type**\
        \ | **Required** |\n| --- | --- | --- | --- |\n| `OTPSigninRequest` | This\
        \ must be passed as `true` to sign the user in using OTP data. | `Boolean`\
        \ | Yes |\n| `OTPSigninData` | Pass the `Code` and `FieldContent` together\
        \ with the `OTP` (received on the user’s phone or email) from the response\
        \ of the Get Sign In OTP API. | `String` | Yes |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OTPSigninRequest:
                  type: boolean
                  description: This must be passed as `true` to sign the user in using
                    OTP data.
                OTPSigninData:
                  type: object
                  properties:
                    Otp:
                      type: string
                    FieldContent:
                      type: string
                    Code:
                      type: string
                  description: Pass the `Code` and `FieldContent` together with the
                    `OTP` (received on the user’s phone or email) from the response
                    of the Get Sign In OTP API.
              required:
              - OTPSigninData
              - OTPSigninRequest
            example:
              OTPSigninRequest: true
              OTPSigninData:
                Otp: '132816'
                FieldContent: johnwick@acme.com
                Code: QzhCS3hsTmVzMU9JbmxvUUlVaHRRQlgwSW5ES2dKRzJaVGtidHFuTDdZR3l1RG9BdUZMeWhpWFNtMG51T2kzU0lTUm1YVy8zN0dpWTcvbEV1UjU1a1pwZmFZOTl2UFYyL212SmduaDdZblZlR1B3SUJLQXJVUldkL0k3Rmx5NVhYazY2VDJCcGxMeUxRK1cxTFEyQ1p0NmZ6NUZJelI5cHNGOFVyaGtvL21jcW5CRzlTVW1USGFmSVpOcEFZTEtGTXpuaFY3Rkt1VjZhLy9rQURWYnIwelVVOUppTlByWGsyWk1SWXNrR0RVR3ltbXR1bFl4K3VJcEd2dHhOb2k2Z01NcVgzQ0E4QnpYMXFnMEZYbXN1dVE9PQ==
      x-original-path: /api/Authentication/V2/Signin
      x-original-name: Sign In with OTP
      x-original-method: post
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Authentication/V2/SecureForgotPassword:
    post:
      summary: Forgot Password
      operationId: forgot_password
      tags:
      - Authentication
      responses:
        '200':
          description: Forgot Password via Phone
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                    description: The overall result of the request. Returns `Success`
                      when the password reset link is sent successfully.
                  Message:
                    type: string
                    description: A status message indicating the result of the request.
                      Returns `Reset link sent successfully` on success.
              example:
                Status: Success
                Message: Reset link sent successfully
      description: "This API enables you to send a password reset Email/SMS when a\
        \ user forgets their password. The email will be sent to the user based on\
        \ the `EmailAddress` or `Phone` (registered email address or phone number)\
        \ posted in the JSON body.\n\n> **Note:** The `LeadId` and `TemporaryPassword`\
        \ received from the reset email when this API is triggered (read the URL in\
        \ the reset email for these parameters) must be passed in the [Reset Password\
        \ API](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/nmd175k/reset-password?action=share&source=copy-link&creator=39502170&ctx=documentation)\
        \ to create a new password. \n  \n\n## Payload\n\n| **Parameter** | **Description**\
        \ | **Data Type** | **Required** |\n| --- | --- | --- | --- |\n| `EmailAddress`\
        \ | Pass the user’s registered email address. | `String` | Pass either `EmailAddress`\
        \ or `SearchKeyData` |\n| `SearchKeyData` | Alternatively, you can pass the\
        \ `SearchKeyData` property and include the `SchemaName` and `Value` of any\
        \ unique lead field. A password reset email will be sent to the email address\
        \ associated with the lead that matches the `SearchKeyData`. | `String` |\
        \ Pass either `EmailAddress` or `SearchKeyData` |\n| `RecipientField` | If\
        \ you want to send the password reset link to a phone or an alternative email,\
        \ along with the `SearchKeyData`, also pass the `RecipientField` property\
        \ and include the `SchemaName` of the field you want to send the link to.\
        \ The field must be of data type phone or email. | `String` | No |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                EmailAddress:
                  type: string
                  description: 'Pass the user’s registered email address.


                    > Note: You must pass either `EmailAddress` or `SearchKeyData`.'
                SearchKeyData:
                  type: array
                  items:
                    properties:
                      SchemaName:
                        type: string
                      Value:
                        type: string
                    type: object
                  description: 'Alternatively, you can pass the `SearchKeyData` property
                    and include the `SchemaName` and `Value` of any unique lead field.
                    A password reset email will be sent to the email address associated
                    with the lead that matches the `SearchKeyData`.


                    > Note: You must pass either `EmailAddress` or `SearchKeyData`.'
                RecipientField:
                  type: object
                  description: If you want to send the password reset link to a phone
                    or an alternative email, along with the `SearchKeyData`, also
                    pass the `RecipientField` property and include the `SchemaName`
                    of the field you want to send the link to. The field must be of
                    data type phone or email. Set `IsRegFormComponent` to true.
                  properties:
                    SchemaName:
                      type: string
                IsRegFormComponent:
                  type: boolean
                  default: 'false'
                  description: 'If you''re sending the `RecipientField` property,
                    set `IsRegFormComponent` to `true`. '
            example:
              EmailAddress: johnwick@acme.com
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Authentication/V2/ResetPassword:
    post:
      summary: Reset Password
      operationId: reset_password
      tags:
      - Authentication
      responses:
        '200':
          description: Reset Password
          content:
            application/json:
              schema:
                type: object
                properties:
                  IsSuccessful:
                    type: boolean
                    description: Indicates whether the password change request was
                      processed successfully. Returns `true` on success.
                  ResponseText:
                    type: string
                    description: A status message indicating the result of the request.
                      Returns `Password changed successfully` on success.
              example:
                IsSuccessful: true
                ResponseText: Password changed successfully
      description: "This API resets the lead's password. This API must be called after\
        \ the [Forgot Password](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/h4p7ihl/forgot-password?action=share&source=copy-link&creator=39502170&ctx=documentation)\
        \ API.\n\n> **Note:** Pass the `LeadId` and `TemporaryPassword` received from\
        \ the Forgot Password API reset email/SMS (read the URL in the reset email\
        \ sent to your email address or phone number for these parameters). \n  \n\
        \n## Payload\n\n| Parameter | Description | Data Type | Required |\n| ---\
        \ | --- | --- | --- |\n| `Password` | Pass the user’s new password here. |\
        \ `String` | Yes |\n| `LeadId` | Pass the user’s lead id received in the Forgot\
        \ Password API. | `String` | Yes |\n| `TemporaryPassword` | Pass the temporary\
        \ password received in the Forgot Password API. | `String` | Yes |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Password:
                  type: string
                  description: Pass the user’s new password here.
                LeadId:
                  type: string
                  description: Pass the user’s lead id received in the Portal's Forgot
                    Password API.
                TemporaryPassword:
                  type: string
                  description: Pass the temporary password received in the Portal's
                    Forgot Password API.
              required:
              - Password
              - LeadId
              - TemporaryPassword
            example:
              Password: NewSamplepassword@123
              LeadId: a7db14f7-6c09-460b-9f46-d2b59a2976d5
              TemporaryPassword: 12078b6f730c675484812414f8cd806a154b87735472460e1ff46126eed3f14c
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Settings/V2/ChangePassword:
    post:
      summary: Change Password
      operationId: change_password
      tags:
      - Settings
      responses:
        '200':
          description: Change Password
          content:
            application/json:
              schema:
                type: object
                properties:
                  IsSuccessful:
                    type: boolean
                    description: Indicates whether the password change request was
                      processed successfully. Returns `true` on success.
                  ResponseText:
                    type: string
                    description: A status message indicating the result of the request.
                      Returns `Password changed successfully` on success.
              example:
                IsSuccessful: true
                ResponseText: Password changed successfully
      description: 'Use this API to let users change their passwords once they’ve
        [signed in](https://www.postman.com/leadsquaredapi/leadsquared-public-apis/request/105zbkp/sign-in-with-password?action=share&source=copy-link&creator=39502170&ctx=documentation)
        to your portal.


        ## Payload


        | **Parameter** | **Description** | **Data type** | **Required** |

        | --- | --- | --- | --- |

        | `CurrentPassword` | Pass the user’s current password. | `String` | Yes |

        | `NewPassword` | Pass the user’s new password. | `String` | Yes |'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                CurrentPassword:
                  type: string
                  description: Pass the user’s current password.
                NewPassword:
                  type: string
                  description: Pass the user’s new password.
              required:
              - CurrentPassword
              - NewPassword
            example:
              CurrentPassword: Samplepassword@123
              NewPassword: NewSamplepassword@123
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Settings/V2/SignOut:
    post:
      summary: Sign Out
      operationId: sign_out
      tags:
      - Settings
      responses:
        '200':
          description: Sign Out
          content:
            application/json:
              schema:
                type: object
                properties:
                  IsSuccessful:
                    type: boolean
                    description: Indicates whether the Sign Out request was processed
                      successfully. Returns true on success.
                  ResponseText:
                    type: string
                    description: A status message indicating the result of the request.
                      Returns `Lead signed out successfully` on success.
              example:
                IsSuccessful: true
                ResponseText: Lead signed out successfully
      description: 'This API invalidates the lead''s logged in session and logs the
        lead out.


        > **Note:** You must pass an empty payload.'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example: {}
      security:
      - Auth: []
        RegistrationToken: []
        PortalId: []
  /api/Access/GetAutoLoginAuthkey:
    get:
      summary: Portal Auto Login – Generate Tenant Auth Key
      operationId: portal_auto_login_generate_tenant_auth_key
      tags:
      - Auto Login
      responses:
        '200':
          description: Get Auto Login Auth Key
          content:
            application/json:
              schema:
                type: string
              example: b42785492bd50772cab56b1d0a945565443814f10bcee91c643aa24
      description: This API generates Auto Login Auth Token which needs to be passed
        in Generate API. This doesn't have any expiration time
      parameters: []
      security:
      - AccessKey: []
        SecretKey: []
  /api/AutoLogin/Generate:
    post:
      summary: Portal Auto Login – Generate Lead-Level Auth Key
      operationId: portal_auto_login_generate_lead_level_auth_key
      tags:
      - Auto Login
      responses:
        '200':
          description: Portal Auto Login – Generate Lead-Level Auth Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  AuthKey:
                    type: string
                    description: 'Thus is an alpha-numeric auth key. Append this auth
                      key to the target portal page URL along with the `LeadId` and
                      `PortalId` (e.g., `apply.lsqportal.com?leadId=&portalId=&authKey=`)
                      and share it with the lead (e.g., via email, SMS, etc.).


                      The auth key will have 4 hours of default expiration time. To
                      change this duration, contact your account manager.

                      '
                  LeadId:
                    type: string
                    description: The unique identifier of the lead.
              example:
                AuthKey: NE9YM2pmWHREQ0hLVXZ5RzdxZ0YzcmZZV2xxWGxsbXNNdWx5MTllRlhyTVFQOUtMcktNL2tXbG5WQXU3Z3lkOEVRb3BxM2NNRk9pUGlkVUxacE1DTXpoWkMvOU5PTUVkbDhGNFJoSkxqTzdUeVdTbUxlM0VxajhsVy80R2tVUXFxNTlqamlGSGdtTkFtNFRFY1l3SE0wc0o3YW5GSjZwY2Q3dnEzck92WDdLU21vSVZTQ1VYL2l5VDh5QVVMc0dCZVUyUTE4TlBBckdDZng3bUlqcG5YUEYwaXNkWEhwMWlCWmtQSlVuaUhNS1JFVGwrWGtBTGZRY1YxMVBxdUs2OG9TeHFpcXdDVWcyY25IQWN2Q2pIZjYxQWxEV0tHSGkwYW04Q0F4Nk1EcjYxRWJhcGJ5Z1hJZkQxYmJrRy9hb2NLTTNRQ2NsU1dwVGw0dHFaRzcwRmJYc1BCcUdEcmd4QWNETXpCaG80UzB5QU5wOThPdHpDSnphU2RKNG5ONWN5aWcvKzhxWnlyZG5EYVMxUE1xNGIwMFMzQ2FJRFVkRzJlcFBVMm5Gc0tYdktDT0xEMTJ4TG9Tdmh1NW9Oazk0Mm1JY2xudU8zcVNKQXNEcEY1UmxFU1VTVGdrdWYwWUpaZGZCNHhqUFV5N2VzSmJLMHlySFZGd0pEa0JpY0xrRkd3NUl2bGRaRW1jdzhFelY1RzR2NGkydzdDVHhBTVpCWHlmdDVIYm9PQ1BJRlBnOGxDSEJoYjZZR2ltUVBWUHFyaDBqRlBXTm5IV05ReW1KVmVlQjJhano2VXljOFJHenR3S3ZwZFk1RDgzanBvbGNJU1lObTIyYzhHTVJ5amp4cGJRc0pSWW1tWFJrM21BTU9ieWJOL2Yzd3ZsNmhhMHFETXh2ZVR5UG96QlBTclBWN1Jxa3IxVEI0b3RFR0drT0NuTzZPTWhLQVZrSm05Ri8wTG00UnJvVnIwdC9MVWE2Z1Q2d1dkNG16V28wWk8zUUVtc2JTN0UzNjdnb1IweXpuUVVNSjNRMnFMVytzRzBzWWlRU0dJQ0hFemZrei9zcnpURFNpaExpMGVvM3ZVZkViR2V0aHRIOGExYTRwSDRtemxVaFVFUTVHR3JuZ1N2N08xckhCdkY3NjdXTE11bmZBaHoyM08wdmozSlZiTTBHczZORUZlR05GZVhrRlcxYzk=
                LeadId: d17f0128-8ea2-4828-a284-3432052913ec
      description: "This API generates the Lead private token for particular Portal.\n\
        \n**Note:**\n\n- The response returns an alpha-numeric auth key. Append this\
        \ auth key to the target portal page URL along with the `LeadId` and `PortalId`\
        \ (e.g., `apply.lsqportal.com?leadId=&portalId=&authKey=`) and share it with\
        \ the lead (e.g., via email, SMS, etc.).\n    \n- The auth key will have 4\
        \ hours of default expiration time. To change this duration, contact your\
        \ account manager.\n    \n\n## Payload\n\n| **Parameter** | **Description**\
        \ | **Data Type** | **Required** |\n| --- | --- | --- | --- |\n| `LeadId`\
        \ | Use any of the Retrieve Lead APIs to get the LeadId. | `String` | Yes\
        \ |\n| `PortalId` | You can obtain the portal Id by accessing your LeadSquared\
        \ account and navigating to Workflow>Manage Portals, select a portal and copy\
        \ the portal Id from the page URL. | `String` | Yes |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                LeadId:
                  type: string
                  description: Use any of the Retrieve Lead APIs to get the LeadId.
                PortalId:
                  type: string
                  description: You can obtain the portal Id by accessing your LeadSquared
                    account and navigating to `Workflow>Manage Portals`, select a
                    portal and copy the portal Id from the page URL.
              required:
              - LeadId
              - PortalId
            example:
              LeadId: d17f0128-8ea2-4828-a284-3432052913ec
              PortalId: 20ca63f4-4dbf-11ed-a87f-0a5db97dc116
      security:
      - AuthKey: []
  /api/Widget/RetrieveSnippet:
    get:
      summary: Retrieve Widget Snippet
      operationId: retrieve_widget_snippet
      tags:
      - Widgets
      responses:
        '200':
          description: Retrieve Widget Snippet
          content:
            application/json:
              schema:
                type: string
              example: <div id="lsq-portal-widget-f0600e64-56bd" class="lsq-portal-widget
                lsq-form-widget"><script src="https://portal-widgets.lsqportal.com/assets/bootstrap-widget.js"
                data-widget-id="f0600e64-56bd" data-version-id="15146560-8710" data-formjs="https://forms.lsqportal.com/r21/js/lsq.form.js"
                data-URL="https://portal-widgets.lsqportal.com" onload="window['___lsq-portal-widget-helpers___'].bootstrapLSQWidget(event)"
                charset="utf-8"></script></div>
      description: 'Retrieves the JavaScript snippet for LeadSquared Widgets that
        can be pasted into your website.


        > Note: You must [use the correct API host](https://www.postman.com/leadsquaredapi/workspace/leadsquared-public-apis/folder/39502170-790c0633-8cec-4d5e-8f5b-14a01fea8fd1?action=share&creator=39502170&ctx=documentation&active-environment=39502170-a39a29d0-f0e1-4be8-9191-f01bd917feb4)
        to make successful calls.'
      parameters: []
      security:
      - AccessKey: []
        SecretKey: []
        WidgetId: []
  /api/Widget/Retrieve:
    post:
      summary: Retrieve Widgets
      operationId: retrieve_widgets
      tags:
      - Widgets
      responses:
        '200':
          description: Retrieve Widgets
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalRecords:
                    type: integer
                    description: The total number of widgets returned in the response.
                  WidgetList:
                    type: array
                    items:
                      type: object
                      properties:
                        Id:
                          type: string
                          description: The unique identifier of the widget.
                        Name:
                          type: string
                          description: The display name of the widget.
                        Description:
                          type: string
                          description: A brief description of the widget. Returns
                            an empty string if no description is set.
                    description: A list of widget objects associated with the portal.
              example:
                TotalRecords: 2
                WidgetList:
                - Id: 7bda1ee6-5c4d-11ee
                  Name: Uni Widget
                  Description: ''
                - Id: f0600e64-56bd-11ee
                  Name: University Widget
                  Description: ''
      description: "Retrieves the LeadSquared Widget details of one or more widgets\
        \ (Widget Id, Name, and Description).\n\n> Note: You must [use the correct\
        \ API host](https://www.postman.com/leadsquaredapi/workspace/leadsquared-public-apis/folder/39502170-790c0633-8cec-4d5e-8f5b-14a01fea8fd1?action=share&creator=39502170&ctx=documentation&active-environment=39502170-a39a29d0-f0e1-4be8-9191-f01bd917feb4)\
        \ to make successful calls. \n  \n\n## Payload\n\nAll request parameters are\
        \ **non-mandatory**. If you pass an empty payload, then all the widgets available\
        \ in the manage widgets page will be retrieved.\n\n| Parameter | Description\
        \ | **Data Type** | **Required** |\n| --- | --- | --- | --- |\n| `SearchText`\
        \ | Retrieves widgets based on any string you pass. The string can be the\
        \ widget name or description. | `String` | No |\n| `StatusCode` | Lets you\
        \ retrieve widgets by status –  <br>  <br>\\- `0` represents unpublished widgets\
        \  <br>  <br>\\- `1` represents published widgets | `Integer` | No |\n| `PageIndex`\
        \ & `PageSize` | The results matching your criteria may be large. You can\
        \ fetch the result in blocks of “PageSize” and make multiple calls to the\
        \ API with increasing values of “PageIndex”. For example, you can specify\
        \ “PageIndex”: 1, “PageSize”: 100 for the first call and specify “PageIndex”:\
        \ 2, “PageSize”: 100 for second call. | `Integer` | No |"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Parameter:
                  type: object
                  properties:
                    SearchText:
                      type: string
                      description: Retrieves widgets based on any string you pass.
                        The string can be the widget name or description.
                    StatusCode:
                      type: string
                      description: "Lets you retrieve widgets by status –  \n  \n\
                        - `0` represents unpublished widgets  \n  \n- `1` represents\
                        \ published widgets"
                Paging:
                  type: object
                  properties:
                    PageIndex:
                      type: integer
                    PageSize:
                      type: integer
                  description: 'The results matching your criteria may be large. You
                    can fetch the result in blocks of `PageSize` and make multiple
                    calls to the API with increasing values of `PageIndex`. For example,
                    you can specify `“PageIndex”: 1, “PageSize”: 100` for the first
                    call and specify `“PageIndex”: 2, “PageSize”: 100` for second
                    call.'
            example:
              Parameter:
                SearchText: Uni
                StatusCode: '1'
              Paging:
                PageIndex: 1
                PageSize: 25
      security:
      - AccessKey: []
        SecretKey: []
components:
  securitySchemes:
    RegistrationToken:
      type: apiKey
      in: query
      name: x-lsq-registertoken
      description: The registration token you received form the Portals `Get Portal
        Registration Token` API response.
    Auth:
      type: apiKey
      in: header
      name: Authorization
      description: The public authentication key you receive from the Portals `Get
        Public Auth Key` API response.
    PortalId:
      type: apiKey
      in: header
      name: x-lsq-portalid
      description: You can obtain the `portalId` by accessing your LeadSquared account
        and navigating to `Workflow>Manage Portals`, select a portal and copy the
        portal Id from the page URL.
    AccessKey:
      type: apiKey
      in: query
      name: accessKey
      description: The `accessKey` can be obtained on your LeadSquared dashboard.
        Navigate to `My Account>Settings>API and Webhooks>API Access Keys` section.
    SecretKey:
      type: apiKey
      in: query
      name: secretKey
      description: The `secretKey` can be obtained on your LeadSquared dashboard.
        Navigate to `My Account>Settings>API and Webhooks>API Access Keys` section.
    AuthKey:
      type: apiKey
      in: query
      name: authkey
      description: Auth key obtained from the Portals `Get Auto Login Auth Key` API.
    WidgetId:
      type: apiKey
      in: query
      name: widgetId
      description: Unique identifier of the Widget. The ID will be available in the
        URL when you open a Widget on the Manage Widgets page on the LeadSquared Dashboard.
x-readme: {}
